[package]
name = "vst-from-scratch"
version = "0.1.0"
authors = ["Charles Saracco <crsaracco@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
simplelog = "^0.5.0"
libc = "0.2"

[lib]
name = "vst_from_scratch"
crate-type = ["cdylib"]